### ISSUE TITLE
Jordi's Profile picture is weird AND his donation is listed twice

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#1007]
https://beta.giveth.io/profile/0x1DBA1131000664b884A1Ba238464159892252D3a

2 issues in 1 :-D

**Comment by arbreton** [comment]
2 in 1 is great! 
looking into it right now, i found the root cause of the donations, now uploaded a commit

about the profile picture Jordi needs to re upload the picture, there was a mistake on the upload text, specifying that it needed a 16:9 picture while it really needs 1:1, he needs to reupload 1:1
