### ISSUE TITLE
Make Build scripts accessible to contributors

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1015]
An awesome new Contributor, @Jurek-brisbane:matrix.org on Riot put in a lot of work to write well documented scripts of the build process... here is a dump of that data... I'm not sure where it should go.

[givethBuildStartScripts_2019-09-29.zip](https://github.com/Giveth/giveth-dapp/files/3674808/givethBuildStartScripts_2019-09-29.zip)

**Comment by GriffGreen** [comment]
https://youtu.be/rzLhxxAz73k Jurek even made a video about it!

**Comment by arbreton** [comment]
Updated feathers README to reflect changes! https://github.com/Giveth/feathers-giveth/blob/develop/README.md

**Comment by arbreton** [comment]
Also in the dapp repo https://github.com/Giveth/giveth-dapp/blob/develop/README.md

**Comment by jamespfarrell** [comment]
These scripts are based on Jurek's but for zshell with osx plugin

In order to get this working on zshell you need to [activate the osx plugin](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/osx):

In newer version of MacOS, you may need to [change some security settings](https://gist.github.com/jamespfarrell/6bf20ccd2ffa1821a0108b1559a87c21)
[giveth-build-run.zip](https://github.com/Giveth/giveth-dapp/files/3713795/giveth-build-run.zip)
