### ISSUE TITLE
Remove "sign a message" functions from various places

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-dapp#1021]
Wanted to post this earlier - sorry for that.

There are at least two instances in the DApp where we ask the user to "sign a message":
- create a new profile
- access "my milestones" overview

This function is: 
1. a bit annoying for users that are already signed in, as they have to repeatedly sign a message which hurts UX flow.
2. Giving an error when used with an Aragon agent account from frame.sh (Aragon's wallet)

I suspect that the error lies on frame's side, but then there is still point 1 - hurting the user flow and encouraging drop out.

So if there is no **very critical point** why we use message signing, I would propose to just **remove message signing entirely from the DApp.**

**Comment by bowensanders** [comment]
[Notes I promised to add from today's DAPP meeting about Frame functionality]

- Frame currently does not allow for the ability to use the Aragon Agent addresses on more than one network at once, the address is only operational on the network that the associated Aragon DAO is located, and that Agent address is linked. Because of this, the Giveth DAPP in it's current form is only able to be controlled by a Rinkeby DAO, and can only be donated to from a Mainnet DAO. Significant functionality would have to be added at either just Frame or at both Frame and Aragon to allow cross-network messaging. We can still, however, by removing signatures from the DAPP, prove to Aragon that it may be of use to look into further by controlling giveth from a rinkeby DAO. (We can already currently control Giveth from a non-agent frame controlled address such as a private key.)
- Signatures may not be necessary since all control functions of the DAPP seem to require the use of data-bearing transactions sent by owners / reviewers of DAC/Campaign/Milestone.

**Comment by aminlatifi** [comment]
I know how important is to make frame works with Giveth. But more important is Giveth security. Users authenticate to Giveth by signing a message currently, and removing this authentication is so dangerous. **One can easily fool the dApp with any web3 address without having its private keys**!!!!

Let's take a look at two scenarios. Of course public key of each users is publicly available and attacker can propose milestones on behalf of them without signing a transaction.
More terrible, attacker can reject proposed milestones on behalf of the campaign owner!!!

I can remove "sign a message" functionality now, it needs changes in both feather server and Dapp. But I believe we should be more careful about this. @bowensanders @GriffGreen @geleeroyale @arbreton Please let me know what do you think after considering above scenarios.

**Comment by bowensanders** [comment]
First off, thank you for all your diligence. I agree that security is Paramount and we need to be circumspect about any decision on this area.
Second, we have to look at the way that most people would be identifying their address to the app (which, by January, needs to be addressed additionally because of new upgrades to metamask and the API) would be metamask. It won't inject web3 anymore. 
I don't think that there is any aspect of the app that requires a signature that isn't actually making a blockchain transaction. BS milestones can be declined by the reviewer, and I can't personally think of any way to effectively spoof anything consequential without having possession of private keys.
Also to return to the original conversation, the way that signatures are currently required by the dapp is invasive and cumbersome, just in order to look at anything in the dapp, it hounds the user for signatures from metamask. Something should change about that as it is. The more important point is that the removal of signatures is for testing and seeing if we've forgotten anything we shouldn't have re security by testing it. The extra bonus is that we should really have visceral knowledge of other wallets - whether that's metamask, frame, cipher, status, or others. But it's only one party of a multi part issue we're going to have to solve because of metamask deciding to change their API and functionality.
I think, in this situation, removal of signatures would be "safe enough to test."

**Comment by aminlatifi** [comment]
> First off, thank you for all your diligence. I agree that security is Paramount and we need to be circumspect about any decision on this area.
> Second, we have to look at the way that most people would be identifying their address to the app (which, by January, needs to be addressed additionally because of new upgrades to metamask and the API) would be metamask. It won't inject web3 anymore.
> I don't think that there is any aspect of the app that requires a signature that isn't actually making a blockchain transaction. BS milestones can be declined by the reviewer, and I can't personally think of any way to effectively spoof anything consequential without having possession of private keys.
> Also to return to the original conversation, the way that signatures are currently required by the dapp is invasive and cumbersome, just in order to look at anything in the dapp, it hounds the user for signatures from metamask. Something should change about that as it is. The more important point is that the removal of signatures is for testing and seeing if we've forgotten anything we shouldn't have re security by testing it. The extra bonus is that we should really have visceral knowledge of other wallets - whether that's metamask, frame, cipher, status, or others. But it's only one part of a multi part issue we're going to have to solve because of metamask deciding to change their API and functionality.
> I think, in this situation, removal of signatures would be "safe enough to test."

Thanks @bowensanders for immediate prompt. I would go ahead and remove signature, but would not push the code to develop branches yet. 
It will create separate branches on both feather and dapp for this matter to test more after implemented.
However, I like to clear it more my concern by this scenario: Attacker can write a script which query feather to get all proposed milestones. Then for each record in the result, the script will send a reject query to feather! Of course if authentication is the public key it would be supper easy. Now how terrible is if attacker run this script every second! No one can propose a milestone!!!!

**Comment by aminlatifi** [comment]
I changed code a little to use user public key to authenticate instead of a signed message. Apparently corresponding dialogs are removed too. 
Changed code can be found here
**dapp:** https://github.com/Giveth/giveth-dapp/tree/remove_sign_message
**feather:** https://github.com/aminlatifi/feathers-giveth/tree/remove_sign_message
These two should run together to work. It's just for test and code is not clean yet. We will make code cleaner if we conclude that this approach is correct.

**Comment by arbreton** [comment]
Hello @aminlatifi , 

I would definitely agree that the writes to Mongo should be protected aswell,
I remember we definitely commented about this, i think the solution is to create an alternative authentication system

There is a pull request on feathers about sign in messages automatic, its an EIP, maybe this could be our solution

we can definitely comment more tomorrow on the meeting

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GriffGreen** [comment]
Great discussion here. I like the different authentication solution. I do hope the requests to the user is minimized as much as possible.... I am excited to see what this new authentication is all about... would it just be a cookie type solution? Or is this a blockchain solution....

If we need the sign message thing for a few actions (like proposing/rejecting a milestone) thats not the end of the world.... ideally it would ask for the signature when you click the button to do those actions.

My big question is... we have this thing where the buttons that are displayed are the ones that you can interact with.. if we don't sign the message... Can we still read what address the user has in metamask and display the right buttons for them?

**Comment by arbreton** [comment]
Definitely would be an automatic very hard to crack solution, best case scenario the user doesn’t have any popups or needs to do extra steps, is just behind the scenes

I would agree if we end up concluding that sign in for some reason is needed there we can definitely move it on user click and not a popup to improve the UX

The answer is yes, we just need to connect to the dapp to read the user address


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aminlatifi** [comment]
> Great discussion here. I like the different authentication solution. I do hope the requests to the user is minimized as much as possible.... I am excited to see what this new authentication is all about... would it just be a cookie type solution? Or is this a blockchain solution....
> 
> If we need the sign message thing for a few actions (like proposing/rejecting a milestone) thats not the end of the world.... ideally it would ask for the signature when you click the button to do those actions.
> 
> My big question is... we have this thing where the buttons that are displayed are the ones that you can interact with.. if we don't sign the message... Can we still read what address the user has in metamask and display the right buttons for them?

Thanks for your response
In order to change authentication approach, the link below introduced different approaches and when and how they can be applied. 
https://blog.wetrust.io/designing-user-account-systems-in-ethereum-apps-f824fe625412
Any way we use signing a message so far, but will limit it to when it necessary.

**Comment by GriffGreen** [comment]
We couldnt remove signing txs completely, but we did refactor its use
