### ISSUE TITLE
Milestone Disburse did not happen, erroring out!

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1068]
Turns out this [Milestone ](https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5dcae0a777aad529434f4d6b) didn't go through - the Disburse button still shows but when I (or David, recipient) hit it, we get the error:
![image](https://user-images.githubusercontent.com/39466970/69775196-0d8e7e00-1166-11ea-994c-bbbe2b124f38.png)

Now it's showing up on the bridge and I'm wondering if there's an issue with DAI/SAI to address?
![image](https://user-images.githubusercontent.com/39466970/69775636-52ff7b00-1167-11ea-9aaa-0e53c05ac8a2.png)

**Comment by arbreton** [comment]
I see the record on the bridge aswell!, does the disburse button still showing you mention @Danibelle ?

**Comment by krrisis** [comment]
Because I think this is the same issue, I will add my experience here. The disburse issue indeed first stays and gives an error the second time you press it. After about an hour the transactions appear on the bridge. Once they are there the disburse button disappears in the dapp. 
They however still show up as 'in progress' as you can see below.

![image](https://user-images.githubusercontent.com/6533925/72343592-8c685780-36cf-11ea-885d-91be472bdb0d.png)

**Comment by krrisis** [comment]
same error with this one - could we fix this? it's linked to the fact that the wrong amount was delegated (double) cc @Danibelle https://beta.giveth.io/campaigns/5cb61c74ef66237670c4ee33/milestones/5e4c2a3911b6b12e5cfbad78
