### ISSUE TITLE
Make sure milestone statuses are updated correctly for capped and uncapped milestones

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#1080]
Some of my recently funded milestones (thank you for that!!!) are stuck in strange states. Some have status completed even though they are paid, others in status paying etc. It is a huge mess.

<img width="1910" alt="Screenshot 2019-12-10 at 21 34 02" src="https://user-images.githubusercontent.com/7974813/70581394-db354580-1b95-11ea-9339-c3a9e0ed4efe.png">
<img width="1222" alt="Screenshot 2019-12-10 at 21 33 50" src="https://user-images.githubusercontent.com/7974813/70581395-db354580-1b95-11ea-89fb-e4a8dd4df619.png">

**Comment by GriffGreen** [comment]
@vojtechsimetka were they not paid out?

**Comment by vojtechsimetka** [comment]
In the end I think I was. Not quite sure if everything though but I will check it this week.

**Comment by vojtechsimetka** [comment]
it still however shows wrongly in the dapp

**Comment by GriffGreen** [comment]
old ones would need to be manually corrected

**Comment by arbreton** [comment]
WIP

**Comment by GriffGreen** [comment]
#1161  has a good example of this

**Comment by GriffGreen** [comment]
Amin:- It’s fixed… capped milestones does not need to be funded exactly as much as max amount to be considered fullyFunded! Because frontend precision is limited, sometimes a tiny value remains… So I changed it to ignore that tiny amount.
There is an important point, after collecting/disbursing a milestone it will have “Paid” status if it’s capped and fullyFunded! This logic has been implemented from the beginning… If we want to change that and consider all milestones that has been paid once as “Paid” we should change that in feathers and fix it for all milestones with a ready script
Griff: I would say that if the milestone can’t be funded any more, and its paid out… then it should say “Paid”
Amin: It’s reasonable, but I am thinking if users eventually click the collect/disburse button and the milestone is not fully funded yet. So capped milestones should not be funded after single payment. We should decide that now…
Capped milestones with reviewers vs capped milestones without reviewers
w/ reviewers, the milestone can only be paid once..
Should be marked paid after being paid out, even if it's not fully funded.
w/o reviewers, capped milestones can be paid multiple times
Should still be accepting money until they are fully funded (or 99.5%) or archived
Amin: Yeah, I will apply this scenario :-D!!

**Comment by GriffGreen** [comment]
#1164 might be related

**Comment by GriffGreen** [comment]
Capped milestones with reviewers vs capped milestones without reviewers

**w/ reviewers, the milestone can only be paid once..**
Should be marked paid after being paid out, even if it's not fully funded.
An example: https://beta.giveth.io/campaigns/5b5b38b19737b23ee71c73a6/milestones/5c575f8d8b07881f80342892

**w/o reviewers, capped milestones can be paid multiple times**
Should still be accepting money until
1. they are fully funded 
2. They are funded to 99.8% of the full amount
3. They are archived

**Comment by aminlatifi** [comment]
> Amin:- It’s fixed… capped milestones does not need to be funded exactly as much as max amount to be considered fullyFunded! Because frontend precision is limited, sometimes a tiny value remains… So I changed it to ignore that tiny amount.
> There is an important point, after collecting/disbursing a milestone it will have “Paid” status if it’s capped and fullyFunded! This logic has been implemented from the beginning… If we want to change that and consider all milestones that has been paid once as “Paid” we should change that in feathers and fix it for all milestones with a ready script
> Griff: I would say that if the milestone can’t be funded any more, and its paid out… then it should say “Paid”
> Amin: It’s reasonable, but I am thinking if users eventually click the collect/disburse button and the milestone is not fully funded yet. So capped milestones should not be funded after single payment. We should decide that now…
> Capped milestones with reviewers vs capped milestones without reviewers
> w/ reviewers, the milestone can only be paid once..
> Should be marked paid after being paid out, even if it's not fully funded.
> w/o reviewers, capped milestones can be paid multiple times
> Should still be accepting money until they are fully funded (or 99.5%) or archived
> Amin: Yeah, I will apply this scenario :-D!!

All this is implemented for new milestones, and script updated previous ones.

The point is that by current policy uncapped milestones with reviewer will stay `In Progress` after collect/disburse action. I wonder whether following the same rule for uncapped milestone or not? I mean uncapped milestones with reviewer should not be donated after become complete. @GriffGreen What do you think?

**Comment by aminlatifi** [comment]
The same rules should be applied to uncapped milestones.

**Comment by GriffGreen** [comment]
Capped milestones with reviewers vs capped milestones without reviewers

w/ reviewers, the milestone can only be paid once..
Should be marked paid after being paid out, even if it's not fully funded.
An example: https://beta.giveth.io/campaigns/5b5b38b19737b23ee71c73a6/milestones/5c575f8d8b07881f80342892

w/o reviewers, capped milestones can be paid multiple times
Should still be accepting money until

they are fully funded
They are funded to 99.8% of the full amount
They are archived

**Comment by aminlatifi** [comment]
@horus2021 please test it. Uncapped milestone with reviewer after become complete cannot be donated anymore

**Comment by horus2021** [comment]
It is fixes thanks @aminlatifi .
