### ISSUE TITLE
Wrapping gone bad in Milestone description

### ISSUE THREAD

**Issue by lorelei1** [Giveth/giveth-dapp#1138]
As u can see the text wrapping is cutting off mid-word and making weird gaps
<img width="860" alt="Screen Shot 2020-02-21 at 11 04 21 AM" src="https://user-images.githubusercontent.com/38163206/75063632-27580c80-549a-11ea-959a-ffc7b6467848.png">

**Comment by aminlatifi** [comment]
The user who has created this milestone has pasted some html content inside description part. The pasted content had &nbsp; instead of simple space (empty space). It's the cause that text in description doesn't wrap as expected.
Replacing &nbsp; with space for all entered text maybe dangerous, because if prevents users when they really want.

**Comment by aminlatifi** [comment]
![image](https://user-images.githubusercontent.com/5684607/75883147-c59f8700-5e37-11ea-9809-f561b1ec4e40.png)
