### ISSUE TITLE
FIX ROUNDING BUGS! 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1252]
<img width="1322" alt="Screen Shot 2020-05-11 at 6 33 18 PM" src="https://user-images.githubusercontent.com/14945613/81586578-fc54c900-93b5-11ea-9248-54debe333a3e.png">
We need to start forgetting about the dust... its a huge distraction and causes lots of other issues... like #1245

Step 1: Define what rounding we care about:

Dai: 0.001

ETH:0.000001

**Comment by GriffGreen** [comment]
Another weird rounding bug to check out:

Trying to donate 280.16... but now its approving... and probably going to donate 280.160000000000025011 

THAT'S MORE THAN I AGREED TO!!!  ;-)

<img width="1171" alt="Screen Shot 2020-05-11 at 8 51 59 PM" src="https://user-images.githubusercontent.com/14945613/81600215-8b1f1100-93c9-11ea-9eff-ee605c5e9bd7.png">

**Comment by aminlatifi** [comment]
Refs #1176

**Comment by aminlatifi** [comment]
> 001
We cannot query donations greater that cut off values!
Feathers saves amounts as string in DB, because MongoDB doesn't support big numbers. Currently we have a plugin to save BN (BN.js library for working with large number which web3 uses too) numbers, but it just support validation! The plugin doesn't support gte (greater than equal) and other comparison operation which we need to filter very small donations. I tried myself and searched but couldn't find good solution at backend. The only way would be to handle that at front-end.
