### ISSUE TITLE
Bridge Monitor has weird issues

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1254]
....

**Comment by GriffGreen** [comment]
bridge is looking weird... https://bridge.beta.giveth.io/

The Mainnet connections are not working... Anyone got an idea?
<img width="936" alt="Screen Shot 2020-05-24 at 5 55 58 PM" src="https://user-images.githubusercontent.com/14945613/82758633-fe704c00-9de7-11ea-9cf7-d5e488f23622.png">
<img width="932" alt="Screen Shot 2020-05-24 at 5 54 48 PM" src="https://user-images.githubusercontent.com/14945613/82758639-016b3c80-9de8-11ea-87a3-44771d9ff272.png">

**Comment by bowensanders** [comment]
Interesting info here: looking at the windows side by side, I noticed that the block numbers were out of order (the first three at least should not be showing at the top) the numbers DO match up:

<img width="1455" alt="Screen Shot 2020-05-26 at 12 07 09 PM" src="https://user-images.githubusercontent.com/27023908/82940437-ad786900-9f49-11ea-95c6-6d3d6be4ffb7.png">

So I believe the problem is not with the monitor, it is a problem with where the monitor is getting its data from, which is feathers in this case. Something seems to have changed around block 9.9mil - and then seems to have righted itself.

**Comment by bowensanders** [comment]
It does appear that clicking on "block #" allows it to re-sort the values, but even on sort they are out of numerical order for some reason. I can't figure out why this instant, but you can match most of the donations

**Comment by aminlatifi** [comment]
@bowensanders I think bridge monitor sorting function considers `Block Number` values as string! that would be the reason it puts numbers start with 9 on top of others start with 1
I tried to investigate in code and become assure... but I couldn't in short time.
