### ISSUE TITLE
integrate gasstation API

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#13]
we currently send & sign a tx on behalf of the user.

we should show a confirmation dialog before sending the tx

**Comment by satyavh** [comment]
What about the gas price?

**Comment by perissology** [comment]
yep

I set it a 4gwei by default, but I would like to add a call to http://ethgasstation.info/ to get a default, and provider a slider for the user to adjust.

**Comment by GriffGreen** [comment]
I STRONGLY Recommend we use a gas price of 4.01 Gwei... leave the sheeple behind... Also i am losing faith on ethgasprice.info, probably because they are geared towards regualar sends and we are doing a lot of contract calls. T
<img width="735" alt="screen shot 2017-09-29 at 8 04 57 pm" src="https://user-images.githubusercontent.com/14945613/31029343-a25241ee-a551-11e7-92ab-1087b20856d7.png">
he only part that is really relevant for contract calls is:

**Comment by satyavh** [comment]
This seems to be the only available API: https://ethgasstation.info/json/ethgasAPI.json
Which outputs something like this:
```
{
"block_time": 16.753735547907212,
"fastestWait": 0.6,
"avgWait": 1.1,
"fastest": 290,
"blockNum": 4565178,
"speed": 0.720268005145945,
"fastWait": 0.6,
"safeLowWait": 3.2,
"safeLow": 0,
"fast": 200,
"average": 10
}
```

So what should we use?

Because @GriffGreen your suggestion worked 29th sep, but perhaps tomorrow it doesn't. We can't keep hardcoding this value.

**Comment by perissology** [comment]
that's what I would use. We might have to add a multiplier, as that api focuses mostly on simple transfers, and we typically use more gas / tx, but it's a starting point for sure.

**Comment by perissology** [comment]
`GasPriceProvider.js` is where this should go

**Comment by satyavh** [comment]
So `average` then times 2?

**Comment by satyavh** [comment]
arghhh, cors enabled of co(u)rse :-(
