### ISSUE TITLE
UI display for Donation tokens

### ISSUE THREAD

**Issue by perissology** [Giveth/giveth-dapp#143]
currently the `develop` branch of feathers & dapp support donation tokens. When a giver donates to a dac or campaign they will receive tokens for their donation.

We need to build a UI component for the dashboard that displays all the donation tokens a single user owns.

Each dac/campaign entity in feathers contains the fields:
* tokenAddress
* tokenName
* tokenSymbol

There is also a `/tokens` service that contains the token balances. Each entry is a unique on the tokenAddress & userAddress properties.

**Comment by satyavh** [comment]
I think the only place where this makes sense is in the 'My donations' tab.
Because we said we would implement Metamask etc, so you won't see your tokens in the Giveth wallet if you make donations from Metamask. Then you can still see it in my donations tab

**Comment by satyavh** [comment]
What do we want to show here, and why?

**Comment by perissology** [comment]
@vsimetka ?

**Comment by vsimetka** [comment]
**Why:**
Because we should pass a message that Givers receive tokens and they can be used in future (even though they are useless now). Right now I would see them as an achievement/collector items :) (you would be surprised how that motivates some people).

**What:**
I think just a sorted table with total amount, name of the token and link to the Cause/Campaign should be enough for now.

**Comment by satyavh** [comment]
@perissology This is stuck on https://github.com/Giveth/feathers-giveth/issues/59

**Comment by perissology** [comment]
that was fixed yesterday

**Comment by satyavh** [comment]
When I create a new account, I see the tokens of other people. Probably all the tokens in the system

**Comment by vsimetka** [comment]
I've already created issue for that #181
