### ISSUE TITLE
Donate without Registering through MyEtherWallet, MyCrypto

### ISSUE THREAD

**Issue by satyavh** [Giveth/giveth-dapp#145]
Add functionality to the Donate button which would give you an option to donate through MyEtherWallet (just like on our website). The smart contracts need to be altered as well to allow donations from un-registered users.

**Comment by perissology** [comment]
need pass data to mew so the tx calls the `donate` method on the liquidPledging contract with `idGiver = 0` and `idReceiver` = dac/campaign/milestone id.

**Comment by satyavh** [comment]
Soooo what would be the contract address? And the gas limit?

`https://www.myetherwallet.com/?to=0x5ADF43DD006c6C36506e2b2DFA352E60002d22Dc&gaslimit=23000&idGiver=0&idReciever=0CtaM8eIQWeSz1Ed#donate`

**Comment by perissology** [comment]
contract address can be found w/

```getNetwork().then(network => network.liquidPledgingAddress)```

gaslimit should be 550000

for dacs: `idReceiver = dac.delegateId`
for campaign/milestone: `idReceiver = (campaign/milestone).projectId`

**Comment by satyavh** [comment]
Can I pass the amount as well?

**Comment by perissology** [comment]
this doesn't work.

you'll need to call the donate method on the contract. however I'm only taken to the mew send-tx page w/o any data pre-filled.

I'm not sure if you can redirect to the mew contracts page, and pre-fill the data. That would be ideal, as it is a bit scary as a user to have a random looking hex string pre-filled in the data. that string could be anything.

If not, you'll need to generate the data string for the lp.donate method.

another option would be to update each plugin's fallback method to forward to the lp contract. This would allow us to use the send-tx page on mew and just specify the gas & amount. This might be the ideal solution now that every dac/campaign/milestone will have their own plugin contract. They could also use the plugin contract as a donation address.

**Comment by vsimetka** [comment]
Oh right, sorry did not know about the data part, should have tested it all the way. There is definitely a way to put the donation data but still redirect.

What needs to go in the data field?

**Comment by vsimetka** [comment]
What needs to be in the data field?

the URL param is `data` but requires already encoded data string.

**Comment by vsimetka** [comment]
Ideas:
- Send money to just a wallet that calls the donate method on LP.
- Fallback method on LPP.
- Having a proxy contract with button to sent the money from the contract and generate tokens.

**Comment by perissology** [comment]
the `data` would need to be generated depending on the dac/campaign/milestone. 

I'll update this once I add the fallback method to the plugins, as we may not need the `data` field for dacs & campaigns, but I need to test if mew will estimateGas correctly

**Comment by perissology** [comment]
Just an update...

Because of the bridging situation now, this will need to be a contract deployed on the mainnet for each dac/campaign that can forward to the bridge the correct data. It probably isn't worth the cost of deploying a contract for any milestones.

The idea is that the adminId will be set on the mainnet contract. It will have a fallback function that forwards to the bridge if enough gas is provided, otherwise, just collects the funds. At anytime, someone can trigger any funds the contract holds to be sent to the bridge.

This will probably use the delegate proxy pattern to save on deployment costs. Possibly make this an AragonApp as the kernel functionality would be useful to store the current bridge instance to make upgrading the bridge pointer easy for all deployed proxies.
