### ISSUE TITLE
Report issue button is off center

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1459]
Or something is off center

<img width="991" alt="Screen Shot 2020-09-19 at 3 07 39 AM" src="https://user-images.githubusercontent.com/14945613/93655689-53823e80-fa25-11ea-8bb2-14ddf513e542.png">

**Comment by horus2021** [comment]
Not **Report Issue** button neither **Join Giveth** button are off center. Both of them are in center of their own row, but these centers are not aligned. A quick fix can be moving **Report Issue** a bit toward **Manage**, to align them. However, I guess it is not a good fix because
1. **Report Issue** will be getting off center and somebody may feels it is not nice. I am not sure, but we can ask @markoprljic with an artistic eye.
2. Moving **Report Issue** toward **Manage** is not straight forward in CSS. But if a UI designer says it should move we can find a solution. 


![page with drop down menu](https://user-images.githubusercontent.com/65175075/94814150-cc11d380-0405-11eb-9313-2e95a84a2166.png)

**Comment by GriffGreen** [comment]
Can be part of to #1376

**Comment by GriffGreen** [comment]
on center now
