### ISSUE TITLE
Update dependencies to React v16.3.0

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#150]
Edited 11th of April 2018.

**Task:**
Find a way how to update the package.json to use React 16.3.0 without breaking the DApp. You may need to update (and are encourage to) other packages as well. Please wait after the #295 is merged.

**Restrictions:**
- Your code should not have any linting errors.
- Don't break our stuff, we will definitely test your code, but make the first attempt at verifying that your changes did not break any components.
- When trying to do this, things like adding expense items break.

**Reasoning:**
We want the context API: https://reactjs.org/blog/2018/03/29/react-v-16-3.html !!!

**Comment by satyavh** [comment]
I'd assign this low prio, although it is always good to stay with the latest version.

But: this is the React / npm world, incompatibilities between packages will always be an issue. And there's always something new that is the best thing since sliced bread. 

What matters is that we ship good software and the Dapp is solid. People could always ship good software, so imo there's no reason we can't do that with React 15 :-)

However what are the security issues you are talking about and how does React 16 solve those?

**Comment by vsimetka** [comment]
Oh sorry I thought I tagged it as a task for contributors to do, definitely low priority and not something we need to solve out now. Right now I no longer get security warnings (I already updated some of the packages) but there are already some requiring react 16 or higher (and for example linter does not work well with versions react of react prior 16).
