### ISSUE TITLE
WBTC and BTC should always be equal

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#1506]
<img width="872" alt="Screen Shot 2020-11-05 at 6 21 09 PM" src="https://user-images.githubusercontent.com/14945613/98274459-b9a23100-1f93-11eb-8b51-3fe70a1e2558.png">

**Comment by aminlatifi** [comment]
@mahdine please help @mohammadranjbar on setting up giveth locally.

**Comment by aminlatifi** [comment]
@mahdine Please help @mohammadranjbar on setting up giveth locally

**Comment by mahdine** [comment]
sure. I'll coordinate with @mohammadranjbar.

**Comment by mohammadranjbar** [comment]
Thanks @mahdine  I'll clone and install everything after that I'll connect with you

**Comment by mohammadranjbar** [comment]
@aminlatifi 

I understood it occurs because in cryptocompare BTC and WBTC has different values

you can check this out:
https://min-api.cryptocompare.com/data/dayAvg?fsym=WBTC&tsym=BTC&toTs=1604880000&extraParams=giveth

Now the response is this:

```
{
    "BTC": 0.9986,
    "ConversionType": {
        "type": "multiply",
        "conversionSymbol": "ETH"
    }
}
```

I think we should use another approach for solving this issue for example multi currency (like :BTC, WBTC) use one rateSymbol for inquiry from cryptocompare,
I'll let you know when the solution finalized
