### ISSUE TITLE
Sunny is not Owner/Manager of Environment DAC but He can Delegate Environment's Fund to again again Campaign

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1637]
The Owner/Manager of [Environment DAC](https://develop.giveth.io/dacs/5ed280b80486523330330e93) is Horus profile but Sunny can delegate Environment's fund. I think this is not acceptable. Only the Horus (profile) as owner should have this power.

**Comment by aminlatifi** [comment]
@horus2021 I cannot find Sunny user in develop db, can you past this account address here?

**Comment by horus2021** [comment]
Sunny Eth addr = 0xB94340E4260803E5178C4E4078B57bc2bA899812

**Comment by horus2021** [comment]
> @horus2021 I cannot find Sunny user in develop db, can you past this account address here?

Sunny Eth addr = 0xB94340E4260803E5178C4E4078B57bc2bA899812

**Comment by aminlatifi** [comment]
@horus2021 I fooled the Dapp to consider me sunny, but app doesn't show any delegation option to me. Neither in a milestone nor a campaign
![image](https://user-images.githubusercontent.com/5684607/104320812-0c4e1b00-54f8-11eb-948d-667dd12d7287.png)

**Comment by aminlatifi** [comment]
@horus2021 It's the query which fetches the list of eligible dacs
![image](https://user-images.githubusercontent.com/5684607/105633057-a48abf00-5e6b-11eb-8d4b-ee5282cff603.png)
Technically it's not possible!
I also create a fresh account and donated to DAC, couldn't delegate it to campaign.
There is a remote change wrong data was created by simulation script new versions, if you still see the bug is it possible to send me sunny account private key?

**Comment by horus2021** [comment]
I cannot see this bug again! Seemingly it's a bug due to simultaion script. @aminlatifi also cannot see this bug with sunny private key in his machne.

**Comment by horus2021** [comment]
I see it when I switch between sunny and Horus profile in my machine. I guess something that remains in metamask cause this glitch. In practice, the probability of this type of switching by one person in one machine is near zero so we can forget this issue.
