### ISSUE TITLE
Email to Milestone Manager When he/she Proposes (Creates) a Milestone

### ISSUE THREAD

**Issue by horus2021** [Giveth/giveth-dapp#1734]
In fact, this email is like a confirmation for Milesotone Manager that your request to create a milestone is registered in Giveht waiting for acceptance by Campaign Manager.

**Comment by laurenluz** [comment]
subject: ‘Giveth - Your Milestone Proposal has been sent!’
secretIntro: ‘Your proposed Milestone ${milestoneTitle} has been submitted for review!’
title: ‘Finger Crossed!’
text: ‘Your proposed Milestone ${milestoneTitle} has been submitted for review! We’ll let you know if the Milestone is approved by the reviewer so you can start raising funds.’
Cta: ‘Manage your Milestones'

**Comment by laurenluz** [comment]
subject: ‘Giveth - Your Milestone Proposal has been sent!’
secretIntro: ‘Your proposed Milestone ${milestoneTitle} has been submitted for review!’
title: ‘Finger Crossed!’
text: ‘Your proposed Milestone ${milestoneTitle} has been submitted for review! We’ll let you know if the Milestone is accepted by the Campaign Manager so you can start raising funds.’
Cta: ‘Manage your Milestones'

@mohammadranjbarz I had to change the text because there was a mistake, can you update please? :)

**Comment by mohammadranjbarz** [comment]
Sure @laurenluz 
Thanks.

**Comment by MoeNick** [comment]
> Sure @laurenluz
> Thanks.

@mohammadranjbarz shall u pls move it to uat if you did it?

**Comment by mohammadranjbarz** [comment]
@MoeNick 
Sure after merging with develop I'll let you know

**Comment by MoeNick** [comment]
@WhyldWanderer @laurenluz can you go forward test this on develop? 
tnx

**Comment by MoeNick** [comment]
I tested it myself, It's OK.
