### ISSUE TITLE
Giveth Gmail filling with Firebase Alert on WOF

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#1818]
The givethdotio@gmail account has been receiving daily alerts on "GivethVideoWallofFame" database for months..
I do not have permission to Edit Rules .. perhaps @laurenluz can as Manager of Giveth on Google Business?

![image](https://user-images.githubusercontent.com/39466970/108776176-e5333200-7516-11eb-82d5-85b193bc592d.png)
![image](https://user-images.githubusercontent.com/39466970/108776266-08f67800-7517-11eb-9ce7-426fbe75ea79.png)
![image](https://user-images.githubusercontent.com/39466970/108776841-c97c5b80-7517-11eb-8230-bbb70733d9a1.png)

**Comment by laurenluz** [comment]
Ok I figured it out... it was sending us an alert about any user being able to read out entire database, but since we're all open source, I think this is not an issue. I just disabled email alerts for this database

![image](https://user-images.githubusercontent.com/75490971/108780457-1539ff80-752e-11eb-8a59-d96bd0d2dd0a.png)
