### ISSUE TITLE
Don't allow user collect/disburse milestone with less than limit

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1886]

**Comment by laurenluz** [comment]
This is similar to #1887 

When user hits "collect" or "disperse"...

Please check that the donation balance is greater than the limit "${value} ${token.symbol}" (fetched from the backend), and if it is not, have a popup that says:

“Oh No!
A minimum donation balance of ${value} ${token.symbol} is required before you can collect or disperse the funds. This is a temporary limitation due to Ethereum Mainnet issues.”

@mohammadranjbarz passing off to you - can you implement?

**Comment by mohammadranjbarz** [comment]
> This is similar to #1887
> 
> When user hits "collect" or "disperse"...
> 
> Please check that the donation balance is greater than the limit "${value} ${token.symbol}" (fetched from the backend), and if it is not, have a popup that says:
> 
> “Oh No!
> A minimum donation balance of ${value} ${token.symbol} is required before you can collect or disperse the funds. This is a temporary limitation due to Ethereum Mainnet issues.”
> 
> @mohammadranjbarz passing off to you - can you implement?

@laurenluz 
Thanks Lauren I would do it but I thinks this epic is not priority for this sprint, maybe next sprint ( Or anytime @aminlatifi  that Amin says)

**Comment by MoeNick** [comment]
Reminder: baner is still at the bottom of the page

**Comment by MoeNick** [comment]
the error is small and go away quickly. 
![image](https://user-images.githubusercontent.com/80677512/114405173-a850f680-9bbb-11eb-8054-6f85c2e2ef93.png)


Shouldn't it be like the one we have on create milestone? As a user I prefer it in the middle, and needs my confirm "OK" before going away. 
what do u think Amin.
