### ISSUE TITLE
Don't allow mark complete a milestone with less than limit balance

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#1887]

**Comment by laurenluz** [comment]
When user clicks "Mark Complete" on this page...

![image](https://user-images.githubusercontent.com/75490971/111365532-376bfc80-8658-11eb-90dd-23c6a265f184.png)

Please check that the donation balance is greater than the limit "${value} ${token.symbol}" (fetched from the backend), and if it is not, have a popup that says:

“Oh No!
A minimum donation balance of ${value} ${token.symbol} is required before you can mark this milestone is complete. This is a temporary limitation due to Ethereum Mainnet issues.”

@mohammadranjbarz can you help to implement this change?

**Comment by mohammadranjbarz** [comment]
> When user clicks "Mark Complete" on this page...
> 
> ![image](https://user-images.githubusercontent.com/75490971/111365532-376bfc80-8658-11eb-90dd-23c6a265f184.png)
> 
> Please check that the donation balance is greater than the limit "${value} ${token.symbol}" (fetched from the backend), and if it is not, have a popup that says:
> 
> “Oh No!
> A minimum donation balance of ${value} ${token.symbol} is required before you can mark this milestone is complete. This is a temporary limitation due to Ethereum Mainnet issues.”
> 
> @mohammadranjbarz can you help to implement this change?

@laurenluz 
Sure Lauren I put it in my tasks

**Comment by MoeNick** [comment]
@RamRamez has reviewed.

**Comment by MoeNick** [comment]
Everey donate-currancy shouldnt be less than 20
