### ISSUE TITLE
Trace not updating? Still says processing but it was paid

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#2178]
![Screen Shot 2021-05-17 at 8 43 20 AM](https://user-images.githubusercontent.com/14945613/118517379-704b4f00-b737-11eb-90e5-7d93930da8fc.png)

https://beta.giveth.io/milestone/jess-milestone-for-communications-and-ecosystem-development

![Screen Shot 2021-05-17 at 8 45 23 AM](https://user-images.githubusercontent.com/14945613/118517661-b30d2700-b737-11eb-9a38-b8fe75ce0b39.png)

**Comment by MoeNick** [comment]
@aminlatifi related to bridge monitor? can you pls tale a look?

**Comment by mohammadranjbarz** [comment]
@GriffGreen 
The trace that you mentioned is ok now, the delay was because this event was at the end of a long queue (syncing with home events from zero time that we start it last night).

but the issue that you mentioned is existed for those traces that `Giveth` didn't pay the payout transactions, that I'm working on that
