### ISSUE TITLE
I delegated 3100 but only 1736.508 DAI showed up?!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#2236]
https://beta.giveth.io/milestone/dan-trusted-seeds-gardener-core-team

<img width="951" alt="Screen Shot 2021-06-02 at 9 47 15 AM" src="https://user-images.githubusercontent.com/14945613/120511366-956ecd00-c387-11eb-8668-cde4b5287441.png">

**Comment by GriffGreen** [comment]
oh weird... ok so his payment isnt stuck, but i delegated 3100, but only 1736.508 DAI showed up!

**Comment by aminlatifi** [comment]
> oh weird... ok so his payment isnt stuck, but i delegated 3100, but only 1736.508 DAI showed up!

@GriffGreen Are you sure the value is not decreased due to scrolling?!! Like the video

https://user-images.githubusercontent.com/5684607/120616440-7a2abd00-c46e-11eb-8680-57174644d848.mov

**Comment by mohammadranjbarz** [comment]
@GriffGreen  @aminlatifi 
I got a dump from the beta database then I run a simulation script to simulate transaction until the last block number before Griff's transaction, then I changed web3PRovider to login instead of Griff then I delegated `3100` from `Common stack society` to this milestone, and I saw that donations amount are ok and sum of them would be 3100, So I conclude that it was user error, I mean after scrolling the amount has changed and Griff didn't understand and signed the transaction with invalid amount

141.274 +450+450+450 +450+150+900+108.726 = 3100

![Screen Shot 1400-03-16 at 14.37.38.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/735ffc44-64d7-4f4a-84e9-3bd207716ddc)

@MoeNick 
I think we can close this issue

**Comment by aminlatifi** [comment]
> @GriffGreen @aminlatifi
> I got a dump from the beta database then I run a simulation script to simulate transaction until the last block number before Griff's transaction, then I changed web3PRovider to login instead of Griff then I delegated `3100` from `Common stack society` to this milestone, and I saw that donations amount are ok and sum of them would be 3100, So I conclude that it was user error, I mean after scrolling the amount has changed and Griff didn't understand and signed the transaction with invalid amount
> 
> 141.274 +450+450+450 +450+150+900+108.726 = 3100
> 
> ![Screen Shot 1400-03-16 at 14.37.38.png](https://camo.githubusercontent.com/9786b4cb45e39a6d253c456567e194e1fe60f6873df626be8e85bdfe3ea03514/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566613765643766623039393433323364316136363033342f37333566666334342d363464372d346634612d383465392d336264323037373136646463)
> 
> @MoeNick
> I think we can close this issue

Thanks @mohammadranjbarz. 
@GriffGreen It's an UI bug which input value is change by scrolling!

**Comment by aminlatifi** [comment]
@RamRamez Please disable input change via up/down keys and scroll
