### ISSUE TITLE
Not sign in button if I close onboard js first popup

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapp#2390]
![image](https://user-images.githubusercontent.com/5684607/125613212-99c0ceb5-fe94-4d82-95d6-a890fef95c96.png)

**Comment by divine-comedian** [comment]
testing on `develop.giveth.io` 

I arrive on this page - 
![image](https://user-images.githubusercontent.com/67759413/126488139-bd922910-46f7-4079-916e-c59ab7c531b5.png)

I click away the onboard JS popup and then I still see the sign in button - 

![image](https://user-images.githubusercontent.com/67759413/126488456-c5828b8c-4639-4ddd-95fe-4d08693d1af0.png)

this issue seems to be resolved
