### ISSUE TITLE
Recipient address field should be blank

### ISSUE THREAD

**Issue by ljg583** [Giveth/giveth-dapp#246]
When you populate a new milestone proposal there is a random address already in the recipient address field.  I think this could cause confusion and may end up with someones ETH going to the wrong/random address. 
 
![screen shot 2018-02-13 at 11 42 38 pm](https://user-images.githubusercontent.com/35914957/36161948-9d571674-1117-11e8-816b-58af6de32bbd.png)

**Comment by vojtechsimetka** [comment]
It is not a random address, it should be your address as it is likely you are the one who also wants to be paid. However, leaving this open as indeed we should make that part more clear and there should be something like:

- [ ] Recipient address is different to my address

and only after clicking this you should see some address.

**Comment by ljg583** [comment]
Okay, thank you for the clarification! I thought the addresses had been for different milestones.  Probably not though.  Just learning the system :)

**Comment by vojtechsimetka** [comment]
**Task**
The recipient address input should not be visible by default. Only after ticking: "Recipient address is different to my address" the input should appear.

**Comment by GriffGreen** [comment]
Bounty for .1 eth by Gov campaign  :-)

**Comment by twmilli** [comment]
A PR should be up for this shortly.

A few questions on design:
* If toggle is on, do we want to prefill with the user address or leave it blank? (my vote is towards leaving it blank)
* I added a gap between the toggle buttons because I thought it looked weird otherwise, do we want this?
* Any feedback you have on how this looks/how we could make it look better would be helpful 😄 


Toggle switched on:
<img width="880" alt="screen shot 2018-04-15 at 5 48 27 pm" src="https://user-images.githubusercontent.com/15217013/38783791-59dae89c-40d5-11e8-9849-c0a6b4a5f1c0.png">

Toggle switched off:
<img width="777" alt="screen shot 2018-04-15 at 5 48 16 pm" src="https://user-images.githubusercontent.com/15217013/38783794-6143dfd0-40d5-11e8-9ab8-c4b2813f3e6d.png">

**Comment by vojtechsimetka** [comment]
Oh sorry I missed this. I think you are on right track in the PR.

**Comment by twmilli** [comment]
Can we close this ? I believe it got merged.

**Comment by vojtechsimetka** [comment]
Yeah, forgot about this issue :).

**Comment by GriffGreen** [comment]
@twmilli do you want to propose a milestone for this using our dapp? It might be fun :-D You can say no tho, and I will.

Make sure to propose it to the Governance campaign :-D
