### ISSUE TITLE
Improvement/Bug fixes prioritisation

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#264]
In the last DApp meeting we have decided that every team member can name 3 problems they would like to have fixed. The top n problems named will be prioritised (we reserve right to discard some) and fixed either by the devteam or assigned bounty and offered to contributors. Please provide as much description as possible ideally with screenshots and if there is already issue with this problem, please link it.

If anyone feels like making the list longer, feel free but mind you that we may decide to only pick first 3. Also @GriffGreen you can write your priority list here as well.

**Comment by geleeroyale** [comment]
Submitted my first **want for superdemo** and converted this issue into an epic to make it easier for you guys to track the requested issues. Hope that's ok 😇

**Comment by krrisis** [comment]
https://github.com/Giveth/giveth-dapp/issues/259
https://github.com/Giveth/giveth-dapp/issues/229 
https://github.com/Giveth/giveth-dapp/issues/109


https://github.com/Giveth/giveth-dapp/issues/265 Fixed by kay I think? 
https://github.com/Giveth/giveth-dapp/issues/276  -> doesn't count, is a quicky
