### ISSUE TITLE
Unable to select "Unknown" as a recipient

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#277]
Not needed before edcon (unless its easy):

I would like to be able to propose a milestone without having to choose a recipient, so that i can link to it and search for a person to take it like a bounty :-D

**Comment by vojtechsimetka** [comment]
@satyavh maybe this should be considered in the Milestone LPP plugin redesign?

**Comment by GriffGreen** [comment]
what would be cool is if the recipient could be unknown and the date even be today or in the future and then the campaing manager, when they accept it, they can lock in the recipient AND the date.... :-D 

That would not require a change to the Milestone plugin

**Comment by perissology** [comment]
exactly, that way wouldn't require changes. You can also set yourself to the recipient, then call change recipient when you've found someone. However if that person doesn't come through, you would need to cancel the milestone as only the recipient can change themselves

**Comment by GriffGreen** [comment]
that would require some UI and UX work... just adding "To be determined later" wouldn't need any new UX and would be more true to the use case of bounties.

Also... there is this auto acceptance thing that happens when the campaign manager proposes a milestone... this feature would allow that to be optional.

Here is an example of me needing this feature:
https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/jxeQyGtQo00c5Pdf

I knew i would have to cancel it no matter what :-( but it was such a nice milestone.

**Comment by vojtechsimetka** [comment]
OK this makes sense now, I'll make a contributors issue out of this on Monday.

**Comment by vojtechsimetka** [comment]
This could be just a UI feature, but it would not allow users to donate money as the milestone is not yet deployed. We could make the recipient to be the Milestone Manager but don't display it as such. Instead show as `To be determined later`. The Milestone Manager can not pay it to himself and has to change recipient. The problem is, that in current implementation the recipient needs to agree (and that would likely be a HW wallet). So since modification of the SC is needed, maybe we can find better solution. To be discussed in the next meeting.

**Comment by GriffGreen** [comment]
being implemented in #517
