### ISSUE TITLE
Expenses and regular reward milestones don't work well together

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#286]
when adding expenses you can only add a milestone by adding 'new item', is confusing if you have milestone with expenses

**Comment by vojtechsimetka** [comment]
Can you explain it better? I am not sure I understand.

**Comment by vojtechsimetka** [comment]
After discussion with Kris, the problem is that the itemized and non-itemized Milestone behave differently. They should be unified and by default you need to provide 1 item with possibility to add more.

**Impact right now and workaround:**
When combining regular reward and expenses it you have to list your regular reward as one of the items with description.

**Comment by horus2021** [comment]
I need to play with Dapp to understand this bug. It is not crystal clear for me.

**Comment by krrisis** [comment]
outdated - closing this
