### ISSUE TITLE
Campaign Manager's can't change picture of milestones proposed by somebody else

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#347]
## Description of the Issue:
When Campaign Manager edits a milestone that has been proposed by someone else, one of the fields they can change id the Milestone image. However, when they save the milestone, the new image is not shown.

## Expected Behavior:
Campaign Manager should be able to upload new image for milestones that are proposed, in progress or in review.

## To replicate:
1. Create campaign with account A
2. Propose milestone with account B in the campaign
3. With account A edit the milestone and try uploading new image
4. Once saved, view the milestone

## Original issue text
at least not by the campaign reviewer for: https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/ydpe0psxgE4flYbf/edit

I tired to change it to this file: 
![1](https://user-images.githubusercontent.com/14945613/39787122-9f4c22a0-52d8-11e8-9b39-62c1e685399f.jpg)

But it wouldnt fly... same old pic is still there but the text changed.... then after i tried to go back to my milestones page i got the green dot of death

**Comment by vojtechsimetka** [comment]
Uh I guess the images can only be uploaded by milestone owner? We may have missed that one.

**Comment by vojtechsimetka** [comment]
## Description of the Issue:
When Campaign Manager edits a milestone that has been proposed by someone else, one of the fields they can change id the Milestone image. However, when they save the milestone, the new image is not shown.

## Expected Behavior:
Campaign Manager should be able to upload new image for milestones that are proposed, in progress or in review.

## To replicate:
1. Create campaign with account A
2. Propose milestone with account B in the campaign
3. With account A edit the milestone and try uploading new image
4. Once saved, view the milestone

**Comment by perissology** [comment]
fixed in feathers https://github.com/Giveth/feathers-giveth/commit/683df00c1e1adc3c7e08e38779ea63d3acc60ce6
