### ISSUE TITLE
Long term: Need a way to donate to Bounties.network, Gitcoin and other bounties

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#379]
look at this awesome bounty: https://beta.bounties.network/bounty/v1/592

Might be interesting to even top up some DAI into this bounty to see how their dapp works.

would be nice if we could integrate into these platforms... i imagine we would need a different type of milestone plugin to play well with them.... but it might be easiest to integrate a very simple milestone for Reg rewards and this type of other network, where the money is just being sent to another address, no need to mark complete or review... as this is done in the contract the money is being sent to.

@perissology: 
The feature I want to confirm that we have in place is that the person withdrawing funds from the bridge has the ability to directly send ETH or Tokens to addresses that are not the person initiating the withdraw :-D

**Comment by vojtechsimetka** [comment]
Good thought for about 3 months from now. Right now we try to focus and limit the scope of the DApp as we discussed. Moving to icebox.

As for your question, in the UI withdrawing does not ask you address and withdraws is to your DApp address. This limitation is created in UI to simplify the flow, but may change soon.

**Comment by perissology** [comment]
@GriffGreen the ability to specify an address to send the tokens/eth to on the home network when withdrawing from the foreign network?

If so, that's not currently implemented, but it is something I thought about doing. Basically when we call `ForeignBridge.withdraw()` we could specify an address that the `authorizedPayment` would be sent to on the home network.

This issue is that we could possibly end up with payments in the `HomeBridge` that are never collected b/c we have no way of notifying the specified address. Unless we add a function to the `HomeBridge` contract `sendPayments(paymentIds)` that would transfer the specified payments to the `dest` address if the payment is payable.

**Comment by perissology** [comment]
okay, so the contracts have been updated to allow this. When you withdraw a milestone, it is directly transferred to the bridge now.

The home network bridge will allow anyone to push authorizedPayments (barring a reality check from adria), therefore you can set the recipient of a milestone to any address and the funds will be transferred to that address on mainnet upon withdraw.

We probably need to update the ui to allow the milestoneManager to initiate the withdraw (thus pushing the funds to the recipient)
