### ISSUE TITLE
Smart Contract Upgrades

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#517]
There is an awesome milestone talking about potential upgrades: https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5bde03f68c322044ef55f10d

I would like to add to it a few things :-D

SCOPE CREEP!

1. Updating the bridge contract: To address #516 and #478 we need to make sure there is an easy way for people to donate to a milestone or campaign by sending funds directly to an Ethereum address (and then we can even display a qr code!)... This will get especially complicated for tokens... but I hope a solution can be engineered :-D

2. Make it easy for a milestone to send money to a campaign (this is probably a UI thing?) 

3. Make a Milestone contract that allows marking milestone complete and the reviewer to be optional... so that basically, if money is pledged to the milestone, it can be instantly withdrawn.

**Comment by perissology** [comment]
> Make it easy for a milestone to send money to a campaign (this is probably a UI thing?)

This is already #11 in the milestone. However I still need to verify what would happen in the scenario that the recipient campaign was canceled, especially if it wasn't the parent campaign. I need to investigate further to assess the feasibility of this.

> Make a Milestone contract that allows marking milestone complete and the reviewer to be optional... so that basically, if money is pledged to the milestone, it can be instantly withdrawn.

I think simplifying the contract to a single optional reviewer (opposed to the current 2 reviewer system) makes sense. The ui would default to the campaign manager as the reviewer, but allow removing the reviewer altogether or setting to any address.

> Updating the bridge contract: To address #516 and #478

This is already possible and not too difficult. However there are a few things that need to be determined, like what happens when the bridge is upgraded? I assume we only want the money to be able to be transferred to the bridge. I think this will be a separate milestone to be tackled after the linked milestone is finished

**Comment by papermache** [comment]
@GriffGreen
