### ISSUE TITLE
Wallet balance should be reactive and consider pending transactions

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#54]
When user tries to donate multiple time, the wallet balance does not indicate any pending donations. For example I have 4 ETH, I donate 2 to one DAC and then I try to donate 1 to a campaign. However, the donation window still shows 4 ETH (it should at least indicate that 2 of that are pending).

**Comment by vojtechsimetka** [comment]
Web3 gt address and pass in pending

**Comment by perissology** [comment]
`web3.eth.getBalance(myAddress, 'pending')`

**Comment by GriffGreen** [comment]
This is easy to do for ETH but for tokens it might be a challenge... its about the pop up that happens when people click the donate button. It shows the balance in two places... 
<img width="969" alt="screen shot 2019-02-27 at 12 18 44 am" src="https://user-images.githubusercontent.com/14945613/53453761-55d90e00-3a25-11e9-8721-33c6edab141c.png">
Here:
<img width="97" alt="screen shot 2019-02-27 at 12 19 02 am" src="https://user-images.githubusercontent.com/14945613/53453759-55d90e00-3a25-11e9-83d1-fd58d0a75c56.png">
And here:
<img width="418" alt="screen shot 2019-02-27 at 12 18 56 am" src="https://user-images.githubusercontent.com/14945613/53453760-55d90e00-3a25-11e9-9734-660e10715b76.png">

Potential solution:
We could store the previous transaction's effect on the balance locally to give the user the feel of instant blocks but it needs to be smart so that when the tx does come thru and changes the balance our "cheat" goes away.
