### ISSUE TITLE
Second DAI Donation failed because it did not ask to approve 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#580]
I tried to donate DAI and the first one worked out great, the second one didnt ask to approve, just straight up asked me to create the transaction to have DAI pulled out of my account, but it failed of course. 
https://etherscan.io/tx/0x25be3a79b777382b1ea29faa9abbf0f40aee7bc85292036d1490940057868d8a
<img width="834" alt="screen shot 2018-12-16 at 2 58 29 pm" src="https://user-images.githubusercontent.com/14945613/50054527-282d3a00-0143-11e9-9f40-0ea7b0167558.png">

I tried it again tho.. and I didnt have the issue... maybe the issue came up because i was donating so quickly that the first tx hadnt fully hit before i was doing the second one... and it just skipped the approve step.. I dont know. But the tx that failed was only 5 blocks after the last tx.
<img width="1153" alt="screen shot 2018-12-16 at 3 09 04 pm" src="https://user-images.githubusercontent.com/14945613/50054813-40eb1f00-0146-11e9-8aac-dfd401fbf13a.png">

IMO this one is worth looking into to see if its a quick fix, but if not, it shouldn't delay the DAI payment.

**Comment by satyavh** [comment]
It looks like we need to wait a couple of blocks / confirmations before the transfer (or approval) can be considered final. Because if the 2nd time you instantly get to the transfer, it means the previous approval was still in place and the previous transfer not really finalise. Sounds like racing conditions.

The quick fix is to create an unlimited approval. We could make a checkbox for that when donating?

Any other solution will be difficult. We currently don't keep track of confirmations, and even if we did it would be quite a UX challenge (conditionally disabling the donate button, 'he you need to wait another 5 minutes before you can donate again...')

**Comment by GriffGreen** [comment]
Do we keep track of time? If the account has donated to anything in the last 5 minutes force an approve? Its not much of a problem for a limited larger approval.. Tho it would be nice to tell them its happening and not just be sitting there.

I'm down for a check box for a limited larger approval.... Maybe 5x the donation amount, with a max of 5000 DAI as a default but allow the user to put in an input for any amount? When this is done and if a Max is included in the spec, then make sure that it is aware that multiple currencies will be used and the max will need to be part of the config for adding a currency.... #futureproof

**Comment by GriffGreen** [comment]
ok so you can queue up 2 transactions in metamask... thats really the answer! instadapp.io

**Comment by papermache** [comment]
@GriffGreen Any updates?

**Comment by GriffGreen** [comment]
Closing because there is a another issue that already talks about getting rid of the waiting time between approve and donate #730
