### ISSUE TITLE
Multiple Expense Milestone: "Attach" button does nothing, cannot create expense

### ISSUE THREAD

**Issue by bowensanders** [Giveth/giveth-dapp#583]
I am unable to "attach" multiple expenses to a new milestone. I've done all the normal tech support stuff to make sure it wasn't me - restart of browser, restart of machine, relogging metamask, making another new milestone, etc. 

Tried making the expense with or without a picture, both do nothing when you press the attach button.

Cancel button works as expected.

<img width="823" alt="screen shot 2018-12-18 at 4 27 24 pm" src="https://user-images.githubusercontent.com/27023908/50191306-29489d80-02e2-11e9-8cc4-3a5f265004c4.png">

**Comment by GriffGreen** [comment]
<img width="1276" alt="screen shot 2018-12-19 at 8 52 50 am" src="https://user-images.githubusercontent.com/14945613/50206397-905e6480-036b-11e9-8095-d0bf944e73ec.png">

I have the same issue, this is what the console logs say: 

Model.js:38 Uncaught TypeError: Cannot read property 'includes' of undefined
    at t.value (Model.js:38)
    at t.set (MilestoneItem.js:65)
    at t.value (AddMilestoneItemModal.jsx:66)
    at t.n.mapModel (index.js:153)
    at t.n.getModel (index.js:107)
    at t.value (AddMilestoneItemModal.jsx:92)
    at onClick (AddMilestoneItemModal.jsx:162)
    at Object.<anonymous> (react-dom.production.min.js:15)
    at Object.invokeGuardedCallback (react-dom.production.min.js:16)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.production.min.js:16)
value @ Model.js:38
set @ MilestoneItem.js:65
value @ AddMilestoneItemModal.jsx:66
n.mapModel @ index.js:153
n.getModel @ index.js:107
value @ AddMilestoneItemModal.jsx:92
onClick @ AddMilestoneItemModal.jsx:162
(anonymous) @ react-dom.production.min.js:15
invokeGuardedCallback @ react-dom.production.min.js:16
invokeGuardedCallbackAndCatchFirstError @ react-dom.production.min.js:16
A @ react-dom.production.min.js:20
T @ react-dom.production.min.js:22
I @ react-dom.production.min.js:22
P @ react-dom.production.min.js:21
L @ react-dom.production.min.js:24
q @ react-dom.production.min.js:24
An @ react-dom.production.min.js:88
Qi @ react-dom.production.min.js:222
Ze @ react-dom.production.min.js:44
In @ react-dom.production.min.js:89
ns @ react-dom.production.min.js:223
Nn @ react-dom.production.min.js:89
Service Worker termination by a timeout timer was canceled because DevTools is attached.
