### ISSUE TITLE
Milestones should be immutable

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#65]
Once created, it should not be possible to change anything in the milestone. Currently I was able to edit not only the description and title but also the reviewer and recipient addresses as well as the necessary amount and validity date.

**Comment by satyavh** [comment]
I think this is up for discussion :-)

**Comment by ojones** [comment]
@perissology from the smart contract side, milestones are immutable correct?

**Comment by satyavh** [comment]
@ojones isn't this up for discussion still?

**Comment by ojones** [comment]
@satyavh sorry changed to bug because it was the easiest path forward. We can't change the contract recipient address. But agree there needs to be some more definition here.

**Comment by GriffGreen** [comment]
For our purposes it might be fair to be able to change everything EXCEPT the Recipient and the Reviewer... this includes the amount of the milestone... because that would allow us to denominate the milestone in USD but pay out in ETH... the nice thing is there is always the Reviewer(s) and the Vault owner.

I hope this isn't going to stop the push to live.

**Comment by vsimetka** [comment]
The amount is anyways just a max amount. I would suggest that it can be changed until marked as complete. From that point on it can no longer be changed.
