### ISSUE TITLE
As a user I want the donations to show the respective amount in fiat.

### ISSUE THREAD

**Issue by vojtechsimetka** [Giveth/giveth-dapp#74]
All the tables with donations in DAC/Campaigns should at least show:

- Date of the donation
- How much in fiat at the date when the money was given (Probably USD by default, but can be changed in user Profile)
 
<img width="1293" alt="screen shot 2017-10-17 at 20 46 42" src="https://user-images.githubusercontent.com/7974813/31683374-22e1d3d6-b37d-11e7-8aea-93cda997888e.png">

**Comment by ojones** [comment]
Let's just start with adding date column for now.

**Comment by satyavh** [comment]
Date column has already been done 2 weeks ago. 
Changing the story title and moving this to icebox. 

I personally feel it is kind of irrelevant to show the donation in fiat at the exchange rate of the date the donation was given. Because in the end all that matters is when you take out the donation and transfer it back to fiat.

The bigger issue here is that you never know how much money you're raising anyways, because eth is so volatile.
