### ISSUE TITLE
Rename Donate buttons to GivETH

### ISSUE THREAD

**Issue by vsimetka** [Giveth/giveth-dapp#83]
This has been decided ages ago and I would like an oppinion from @krrisis , but in general we always wanted to free ourselves from the donate word and use GivETH.

**Comment by GriffGreen** [comment]
Yes but please please please... NOT GivETH  I would prefer all caps GIVETH but Giveth is also cool... but telegraphing a pun is not cool. If they dont get it right away, its ok

**Comment by krrisis** [comment]
'Giveth' is fine with me if you all agreed on this but ... I would add a small explanation under it (for now) so that people know this is the button to click. Fine if they don't get the pun but they MUST understand that with 'Giveth' we mean 'Donate', otherwise they'll think this will bring them to our homepage or something...

**Comment by krrisis** [comment]
Or.. you just make it clear by just make the button 'Give Eth' / 'Give ETH' or simply 'Give' (=my preference)

**Comment by vsimetka** [comment]
The final outcome of the voting (conducted by @satyavh) decided we stay with Donate.
