### ISSUE TITLE
Every dev that tries to run the dapp locally comes across the same switching networks issue

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#844]
i would say 5 out of 6 devs that try to run our dapp locally get hung up on the same thing, it usually goes like:

"Hi all, I'm trying to run giveth dapp locally, and I'm getting the following message
"It looks like your Web3 Provider is connected to the wrong network. Please connect to the Foreign Ganache network."
metamask has localhost:8545 selected
not exactly sure how to deal with this..."

How can we fix this?

**Comment by arbreton** [comment]
Totally agree, personally i have faced difficulties as-well setting up the local environment for the first time, kudos to @ElMejorge for rocket starting me there, otherwise it might have taken me a lot more time to figure that out

An important point is that on the feathers readme https://github.com/Giveth/feathers-giveth/blob/develop/README.md is missing this important information!, that you actually may need to add localhost:8546 to your customRPCs, 

This should be an easy fix on the readme that we can add while we come up some additional aid for developers like one click setups or terminal embedded instructions on install that reminds the developer to add this extra steps

**Comment by GriffGreen** [comment]
add some content to the readme, and at the end of the installation we can add some instructions as well to the dev... that would give them context

**Comment by arbreton** [comment]
Troubleshooting for metamask and deploying feathers aswell.

**Comment by arbreton** [comment]
To be worked, text helpers on console script running

**Comment by papermache** [comment]
@arbreton Any updates?

**Comment by GriffGreen** [comment]
our documentation could always be better but this might already be fixed? @aminlatifi did @mahdine get stuck here too?

**Comment by aminlatifi** [comment]
I taught @mahdine personally, I totally agree to document it somewhere visible to all new devs. I have answered this question many times :)
