### ISSUE TITLE
Have the multi-sig address more widely available for donations

### ISSUE THREAD

**Issue by mroberts10** [Giveth/giveth-dapp#846]
Make this address easily available to help people donate to Giveth.

**Comment by mroberts10** [comment]
If for example its not possible to donate to the DAPP via a campaign or via mobile - you can have it send you an email for when you are back to your desktop.

**Comment by markoprljic** [comment]
Mobile-specific:

1. The page is mobile ready (responsive)
2. no Metamask call that blocks the page to load
3. Click "Donate" button
4. Inform user that web3 is not available on mobile (requires MM), can proceed with a donation but anonymously (show multisig address, option to copy address, can we deeplink for installed wallets and open the app from a link?)
5. Allow user to send the donation link to his email address, like "Ok, I'll do this later" - you want us to remind you and send it to your inbox? Yes/No - if yes email address field and Submit button.

Obviously, this could fit in one screen/step, we'll see.

**This could be a workaround that we can implement throughout the app when we're going to work on  mobile-ready pages.**

**Comment by GriffGreen** [comment]
yep! I would love that to be the default for donating to Giveth if on a browser with no web3... and maybe we should ask people for their addresses, we can do that for everyone... but i think the intention behind this issue is a little more simple than that... we just need to plaster the donation address all over the site and the Giveth DAC donation button could be all over the place too :-D

We just gotta make it easier for people to send us money... :-D

**Comment by markoprljic** [comment]
Actually, yes, the simpler the better. I misunderstood the issue, I see it referring to donating to Giveth, not user created DAC or a campaign. In that case a button to donate should be on the site anyway, but still there's the scenario of donating via mobile.
