### ISSUE TITLE
default screen when there is no web3 provider makes it look like donating ETH is the only option

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#847]
Twice this week we ran into this...

<img width="501" alt="Screen Shot 2019-06-20 at 10 11 22 PM" src="https://user-images.githubusercontent.com/14945613/59878424-895ef000-93a8-11e9-9469-afd03a1ed7ac.png">

because of this:
<img width="901" alt="Screen Shot 2019-06-20 at 10 11 30 PM" src="https://user-images.githubusercontent.com/14945613/59878434-8fed6780-93a8-11e9-9504-887d7f800112.png">

**Comment by aminlatifi** [comment]
@GriffGreen I feel it would be rational if when donation is not possible, only show warning/hint messages. Like these:
![image](https://user-images.githubusercontent.com/5684607/65522595-db5b6880-def7-11e9-9252-377a9647f991.png)

and 

![image](https://user-images.githubusercontent.com/5684607/65522642-ed3d0b80-def7-11e9-90c7-3a99280184ba.png)

@GriffGreen  If you agree, please let me know to commit this. Otherwise I will fix the messages.

**Comment by GriffGreen** [comment]
OH FUCK YEAH!

**Comment by GriffGreen** [comment]
THAT IS GREAT!
