### ISSUE TITLE
Error messages should link to https://github.com/Giveth/giveth-dapp/issues/new

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#872]
Let's get more issues, and faster customer service!

We are about to have a pretty big beta test with Burning man and a lot of people will end up getting milestones sent to them... if we add a link to https://github.com/Giveth/giveth-dapp/issues/new in every error message, we will drastically reduce the barrier to finding out what is broken!

**Comment by arbreton** [comment]
I just saw this, i think it would be great!!!, this is definitely needed and so useful!

**Comment by GriffGreen** [comment]
This should probably be some sort of button or something on the error message that inspires people to click it and fill out a github issue.

**Comment by markoprljic** [comment]
What if a user doesn't have a Github account?

**Comment by aminlatifi** [comment]
> What if a user doesn't have a Github account?

I tried the scenario be similar to VSCode report issue process. On that case (and ours too), user need to create account to report issue.

**Comment by arbreton** [comment]
@markoprljic That is a good observation there, it would not be convenient for a user to create a github account if he is not a developer just to report an issue.

In that case maybe we need to decide if all the buttons are necessary in the report section since it feels a little cluttered, and considering reporting issues on github will only be used by developers, is all the buttons here ok?

<img width="1438" alt="Screen Shot 2019-07-11 at 5 55 42 PM" src="https://user-images.githubusercontent.com/12836187/61153594-884d4a00-a4a0-11e9-9043-067bb1ee84b7.png">

Maybe just the naming? @GriffGreen

**Comment by markoprljic** [comment]
How critical is for us that the report goes straight to Github? How much would this option be used if we allow for that? 
The current popup with all these options is confusing and redundant. 
Can we automatically capture that moment and save it in our Error Log, do we have that?
Devs could run through the log, filter by most occurred and prioritize that way.

I suggest the following format of the error popup (feel free to edit/suggest wording):

Title: Ups, something didn't go well
Body: Don't worry, it's not your fault, it's ours. We have been notified about it and will try to fix this in a timely manner. 

Please try again. 
If this is a recurring problem please submit a report.

Buttons: Try again /  Report (should open a standard form to report the issue)
Link: Close

---

Ideally, it would be good to describe what happened, based on the error code we can inform the user of the type of error that occurred. That doesn't mean we just throw out the Server error message, instead, we rephrase that to something readable and meaningful to the everyday user.

@arbreton @GriffGreen
