### ISSUE TITLE
Amin's milestone doubled up in my my milestone tab...

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#876]
Similar to #639, i have this same milestone twice... its weird that they both say in progress...
<img width="1185" alt="Screen Shot 2019-07-07 at 1 04 49 AM" src="https://user-images.githubusercontent.com/14945613/60761933-cd621e00-a053-11e9-8244-3f78cbd9d236.png">

This one is the real one... I think!?!?!

https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5d1af6c4bd45530e23ad8546

As it has a status update that says Michael approved it

This one:
https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5d1ccb0dbd45530e23ad876e

I think is the clone... the fraud! as it is missing the status update...

But they both show up on https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20
<img width="1283" alt="Screen Shot 2019-07-07 at 1 12 06 AM" src="https://user-images.githubusercontent.com/14945613/60761953-5416fb00-a054-11e9-98f0-8363c0e5f56f.png">

I'm not sure what happened... did Michael approve both but the status update didn't record? Did feathers just put up a shadow milestone that doesnt really exist? Are they both real milestones... oh man whats going on! I'm so confused!

I want to load one of them... but i dont know which one! 

HELP!

**Comment by arbreton** [comment]
Definitely something happened, seems to be a milestone duplication situation, i think we had those cases before, could have been feathers, i will investigate which milestone is the impostor milestone here and apply a quick fix, but we need to investigate further why this happened in the first place

**Comment by arbreton** [comment]
So comparing this two milestones 5d1ccb0dbd45530e23ad876e and 5d1af6c4bd45530e23ad8546, the impostor milestone is definetely **5d1ccb0dbd45530e23ad876e** this is missing 2 fields which are **prevStatus** and **message** which is why the other milestone shows the status update, seems to be that the approval of the milestone went through twice for some reason,

5d1ccb0dbd45530e23ad876e which is faulty was created the minute it was **approved** which shouldn't have occured (probably because it didn't found the milestone to update?)

while 5d1af6c4bd45530e23ad8546 it was created a day before and updated and approved which is ok

seems to be an issue on the milestone approval on feather maybe that creates an item if it can't find and update

Will investigate further!

**Comment by arbreton** [comment]
Short answer the correct milestone is https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5d1af6c4bd45530e23ad8546
@GriffGreen

**Comment by arbreton** [comment]
Removed the duplicate for a quick fix and opened #877

**Comment by GriffGreen** [comment]
Amazing! thx!
