### ISSUE TITLE
Probably the same big number error, can't delegate within the milestone 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapp#893]
<img width="1261" alt="Screen Shot 2019-07-12 at 5 49 21 AM" src="https://user-images.githubusercontent.com/14945613/61101101-e9592b80-a468-11e9-9634-4de76d4b7bb2.png">

You can also see that it seems like i can donate more than 100 too.. the slider's max should only go to 100

**Comment by arbreton** [comment]
Yes it seems that the whole implementation of DelegateMultipleButton has some issues, for some reason the number is on BigNumber instance already but only accepting strings, this only happens when you don't touch the slider, seems to be working if you select an amount with the slider
Uploading corrected version now
