### ISSUE TITLE
Donation not appearing in Art Car Campaign

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapp#903]
Jeffrey got his 50 DAI and donated to the [Art Car Campaign ](https://beta.giveth.io/campaigns/5cfe3366228b71296a491fa7)on 7/17..  but the donation does not seem to be appearing in the Donation list..  Can you take a look at this transaction and see where it went wrong?  0xdc40f2c28e800c51ef78d992c20fa2e67fefddfd8e2675614c78425aef3a0898

![Jeff Art Car](https://user-images.githubusercontent.com/39466970/61492647-60198b80-a977-11e9-9d80-9034315f14f2.jpg)

Transaction says from: 0xaabad8e1774db171b31bc1d923affbef976efa84
That's his MetaMask public key but I can't see where it went after the DAI address.

**Comment by arbreton** [comment]
Hello @Danibelle, i see that Jeffrey only approved but he didn't donated the DAI at the end, there needs to be 2 transactions when donating DAI

This was most likely due to the problem with the server at #904 the Donate transaction didn't came through, so he still has the DAI on his account, he just needs to try to donate again now
