### ISSUE TITLE
Impossible to create a Milestone that accepts donations in all tokens

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-dapp#945]
When I propose a Milestone right now that accepts donations in all tokens, I can hit the 'propose Milestone' button ad infinitum but nothing happens. 

Have changed it to 'eth only' in order to make this Milestone. See screenrecording below. 
Milestone where this happened is [this one](https://beta.giveth.io/campaigns/5cdc668be4ee5d18e7bad987/milestones/5d51873a7d4ad11d4adb5f94) 

Recording of attempt [here](https://www.dropbox.com/s/dipdumal5yb1w5r/issue%20with%20dapp%20milestone.gif?dl=0-)

**Comment by krrisis** [comment]
Had the same issue with [this Milestone](https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5d51af287d4ad11d4adb5fe9) - really wanted to have that one in eth & dai but made it in dai anyways bcs same problem as mentioned above. Hit the button and nothing happens.

**Comment by arbreton** [comment]
Definitely a bug, there is a great phrase from a chinese proverb saying "when you try to bend something that doesn't bend it breaks", working with delicate pieces, we are knowing our limits in terms of fast paced bug fixing (continuous integration), we will need to be way more precise taking a little bit more time on implementation due to this kind of situations, we will try to prolong the development .25x for the sake of stability and quality

Working on this atm!

**Comment by krrisis** [comment]
A dev working on Giveth DApp issues quoting chinese proverbs in his github responses shows that it is a dev who's in the right place, he's working for Giveth.

**Comment by arbreton** [comment]
Still working on a longterm solution

**Comment by arbreton** [comment]
Investigating more in depth this situation

**Comment by arbreton** [comment]
Confirmed now fully working on beta.giveth.io
